name: Generate and Upload PDF Resume

on:
  push:
    branches:
      - main

jobs:
  generate-resume:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Resume CLI and "Professional" Theme
        run: |
          npm install resume-cli
          npm install jsonresume-theme-even

      - name: Generate index.html using "Professional" theme
        run: RESUME_THEME_PATH=./node_modules/jsonresume-theme-even npx resume export index.html --theme even

      - name: Convert HTML to PDF
        uses: fifsky/html-to-pdf-action@master
        with:
          htmlFile: index.html
          outputFile: resume.pdf

      - name: Upload PDF as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: resume-pdf
          path: resume.pdf
